<h1>Afterword</h1>

<p>
First, thank you for picking up this book!
</p>

<p>
Nice to meet you, this is Thai, also known on the web as 0xReki.
</p>

<p>
I started writing on this on February 1st, 2019.
At that time, I simply wrote down what came to my mind just to notice my story isn't turning out that great.
Plus, I was too inspired by another novel.
It was still distinct, but what I wrote felt too similar.
So on June 11th, 2019, I was left with a choice: continue like that and most likely giving up on writing or repivot.
I chose the latter.
Repivoting is a nice term for “Well, that crappy idea I had didn't work out that well. Let's start over from the beginning with another one.”
</p>

<p>
It turns out having lot's ideas for main story writing one thing but getting ideas for an origin or introductory story is surprisingly hard!
By starting over, I like to think I got a somewhat coherent introduction to everything.
Even if it seems Deus Ex Machina at some points.
Unfortunately, some other ideas had to be scrapped.
And it's unlikely they'll ever make it into Crystal Down.
Maybe they'll make it into another story I might be writing in the future, assuming I still think of it a good concept at that time.
</p>

<p>
I'll spare you the details of the endless technical difficulities. For now.
I might share them with you later.
</p>

<p>
To those readers who have read all the way to the end: thank you so much!
</p>

<p>
I hope to see you again in the next volume.
</p>

<p>
Thai “0xReki” Chung
</p>